### ISSUE TITLE
let's combine efforts

### ISSUE THREAD

**Issue by mgumz** [LukasMa/diceware#1]
https://github.com/mgumz/diceware

how about joining forces?

**Comment by lukasmalkmus** [comment]
Haha no problem. I made this entirely for learning purposes. If you have ideas, suggestions or want to do something else leave a comment. Your application seems far more advanced than my small library.

**Comment by mgumz** [comment]
you have travis and tests, i do not.

a user of my version brought up once the idea to have a different separator between the words, something like a-word-and-another-word.

i thought about creating a nice pdf out of the wordlists i have included

lots of ideas and so little time :)
